"""add user alert preferences

Revision ID: 574171aafa1c
Revises: 45ddbea32519
Create Date: 2026-08-12 21:13:59.503105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '574171aafa1c'
down_revision: Union[str, Sequence[str], None] = '45ddbea32519'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'users',
        sa.Column(
            'wants_weather',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true()
        )
    )

    op.add_column(
        'users',
        sa.Column(
            'wants_news',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true()
        )
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'wants_news')
    op.drop_column('users', 'wants_weather')
    # ### end Alembic commands ###
